
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    # -   id: no-commit-to-branch
        # args: ["--branch", "master", "--branch", "main"]
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb", "80000"]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      types: [python]
      args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-PyYAML, types-python-dateutil]

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        types: [python]
        # files: "speclet/.*"
        args: ["--convention", "google", "--add-ignore", "D301,D105"]

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.3
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
    -   id: nbqa-isort
        args: ["--profile=black"]
    -   id: nbqa-black
    -   id: nbqa-mypy
        additional_dependencies: [pydantic, mypy, types-python-dateutil, types-PyYAML]
        types: [jupyter]
    -   id: nbqa-flake8
        args: ["--config=.flake8", "--extend-ignore=E402"]

-   repo: https://github.com/MarcoGorelli/check-execution-order
    rev: v0.1.1
    hooks:
    -   id: check-execution-order
